---
- name: Configure OPS445 VM
  hosts: vmlab
  become: true
  vars:
    seneca_id: yzhang814

  tasks:
    - name: Ensure Apache is installed and up-to-date
      yum:
	name: httpd
        state: latest

    - name: Install EPEL repository
      yum:
	name: epel-release
        state: present

    - name: Remove 'tree' package if present
      yum:
	name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user with sudo access
      user:
	name: "{{ seneca_id }}"
        shell: /bin/bash
        groups: wheel
        state: present
        create_home: yes

    - name: Copy SSH public key to new user
      authorized_key:
        user: "{{ seneca_id }}"
        key: "{{ lookup('file', 'id_rsa.pub') }}"
        state: present

    - name: Create lab folders
